# Generated by Django 3.1.7 on 2021-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pastebin',
            fields=[
                ('key', models.TextField(db_index=True, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('language', models.TextField(blank=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
