# Generated by Django 3.1.7 on 2021-03-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebin',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastebin',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pastebin',
            name='expire_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
