[package]
name = "dpb-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rocket = "0.5.1"
rocket_dyn_templates = { version = "0.2.0", features = ["tera"] }
rocket_db_pools = { version = "0.2.0", features =  ["sqlx_sqlite"] }
chrono = "0.4.38"
